apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer # Esto crea un ELB en AWS automáticamente
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80        # Puerto público externo
    targetPort: 8080 # Puerto interno del contenedor (Nginx)